field: b011195c-bc62-4df7-8300-cb7c75b0b39b # Modules
fieldLayouts:
  d8b19ecc-ff59-4ece-8964-b5508d217306:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c0e1cb94-500f-44d2-a1c7-cc7d6baa219f # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58d0f1d9-cf13-433a-ad6a-66edfc4b766f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3b916bd-5789-49c6-b296-fafff195db01 # Font Family
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e611fd6-21b6-46cf-9b11-1a67bb3ea3b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3a51a1a-2902-4f38-abf9-136d927f4764 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bded0990-90e1-4f29-b07d-ee76e66b3782
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 594a5a75-a205-4c57-ae0a-916e0b4d626a # Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1c99988-7c74-49fe-a62a-f92fb574ac55
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 441f1865-e286-49a2-a6de-747f7d94dd77 # Italic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf3fa8e2-3479-4fff-b067-31c27bad9940
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62f40aee-c9df-49f7-9b79-c8311a3a661c # Underline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af65b76a-4309-48ab-81d5-3d1909c7be54
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d1d927b-04fd-4009-899c-676032602a2f # Font Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5de70ca-d049-43ac-9751-bb039cdd64b1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6b017d19-bc5a-4fc4-8e96-c78eb62e7a2e
        userCondition: null
fields:
  4d1d927b-04fd-4009-899c-676032602a2f: # Font Size
    columnSuffix: cshzodrf
    contentColumnType: text
    fieldGroup: null
    handle: fontSize
    instructions: null
    name: 'Font Size'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  62f40aee-c9df-49f7-9b79-c8311a3a661c: # Underline
    columnSuffix: gzuipfwt
    contentColumnType: string
    fieldGroup: null
    handle: underline
    instructions: null
    name: Underline
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Underline
            -
              - value
              - underline
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - no-underline
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  441f1865-e286-49a2-a6de-747f7d94dd77: # Italic
    columnSuffix: orrcqjjw
    contentColumnType: string
    fieldGroup: null
    handle: italic
    instructions: null
    name: Italic
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Italic
            -
              - value
              - italic
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - not-italic
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  594a5a75-a205-4c57-ae0a-916e0b4d626a: # Bold
    columnSuffix: fddygyre
    contentColumnType: string
    fieldGroup: null
    handle: bold
    instructions: null
    name: Bold
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Bold
            -
              - value
              - font-bold
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - font-regular
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  b3a51a1a-2902-4f38-abf9-136d927f4764: # Color
    columnSuffix: rxlqeihx
    contentColumnType: text
    fieldGroup: null
    handle: color
    instructions: null
    name: Color
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c0e1cb94-500f-44d2-a1c7-cc7d6baa219f: # Body
    columnSuffix: hrykzurk
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c3b916bd-5789-49c6-b296-fafff195db01: # Font Family
    columnSuffix: zodccduf
    contentColumnType: string
    fieldGroup: null
    handle: fontFamily
    instructions: null
    name: 'Font Family'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Figtree
            -
              - value
              - figtree
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Old Standard TT'
            -
              - value
              - oldStandardTt
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Oswald
            -
              - value
              - oswald
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Raleway
            -
              - value
              - raleway
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Template Font'
            -
              - value
              - templateFont
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: moduleH2
name: 'Module H2'
sortOrder: 4
