field: b011195c-bc62-4df7-8300-cb7c75b0b39b # Modules
fieldLayouts:
  2ac75fa0-702b-49e5-8539-b01ece0cdac5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 143c4f1f-9e37-44fa-9f00-08108f8e4e7f # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7d24dcf-4a0e-4017-817a-a91a98cba033
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a5ce730-49a9-4e1a-9069-1cf7fda75f78 # Font family
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f283366-8fb4-419b-81d9-646a761f2a13
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6055be49-84b2-4442-9c3b-6f140a18f3f5 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e73413f3-f763-44eb-95a7-30e4b3e8dbd1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: deaa633c-6eb8-4db0-934c-64809bd2bb1a # Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3273d25-b9ff-4281-aef3-d5f87d551ac5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dcd7591e-83d6-4dc2-b104-3e99c11d90e1 # Italic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a06efbe-cb23-46af-8d27-3ba8872bf5bd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b519d69-fe59-43c2-9d5e-5cd1c77aadbc # Underline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fbeb765-f605-4629-8048-418c69b61066
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f87ab2ab-67db-4234-b933-ce0aeae4f5fb # Font size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b9e01ee-6325-457e-9bd1-521697c9cbf8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c4844a1-c7f6-4d44-ba8f-ac31d53b9a01
        userCondition: null
fields:
  0a5ce730-49a9-4e1a-9069-1cf7fda75f78: # Font family
    columnSuffix: ubhsdrle
    contentColumnType: string
    fieldGroup: null
    handle: fontFamily
    instructions: null
    name: 'Font family'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Figtree
            -
              - value
              - figtree
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Old Standard TT'
            -
              - value
              - oldStandardTt
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Oswald
            -
              - value
              - oswald
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Raleway
            -
              - value
              - raleway
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Template Font'
            -
              - value
              - templateFont
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  2b519d69-fe59-43c2-9d5e-5cd1c77aadbc: # Underline
    columnSuffix: zevxyvyo
    contentColumnType: string
    fieldGroup: null
    handle: underline
    instructions: null
    name: Underline
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Underline
            -
              - value
              - underline
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - no-underline
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  143c4f1f-9e37-44fa-9f00-08108f8e4e7f: # Body
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - pdf
        - powerpoint
        - text
        - word
      defaultUploadLocationSource: 'volume:662158c5-f9fe-47b2-9287-d317af2b0db4' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:662158c5-f9fe-47b2-9287-d317af2b0db4' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:662158c5-f9fe-47b2-9287-d317af2b0db4' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  6055be49-84b2-4442-9c3b-6f140a18f3f5: # Color
    columnSuffix: eunwtapn
    contentColumnType: text
    fieldGroup: null
    handle: color
    instructions: null
    name: Color
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dcd7591e-83d6-4dc2-b104-3e99c11d90e1: # Italic
    columnSuffix: jsatlfbd
    contentColumnType: string
    fieldGroup: null
    handle: italic
    instructions: null
    name: Italic
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Italic
            -
              - value
              - italic
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - not-italic
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  deaa633c-6eb8-4db0-934c-64809bd2bb1a: # Bold
    columnSuffix: tbmcckso
    contentColumnType: string
    fieldGroup: null
    handle: bold
    instructions: null
    name: Bold
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Bold
            -
              - value
              - font-bold
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - font-regular
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  f87ab2ab-67db-4234-b933-ce0aeae4f5fb: # Font size
    columnSuffix: pnbsligd
    contentColumnType: text
    fieldGroup: null
    handle: fontSize
    instructions: null
    name: 'Font size'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: moduleFile
name: 'Module File'
sortOrder: 6
