field: 5ef5528f-2252-48fc-83f8-8482a0bab94a # Template File
fieldLayouts:
  82ccb927-0824-442b-8345-7730b6e501d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f756ef6b-4ea8-4afa-b1e3-e0ce8bb08b3b # Font Family
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1abc2d68-fe85-4d6f-a30b-efbdccee957b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 907dd3e9-07e3-42f2-8ccb-0a1209635961 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02adaf60-d54a-425d-833d-3bc4a09e698e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 405235d2-95a0-4ef8-a938-989e84dd772d # Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fa34a63-5d32-41a3-a90c-3d111fdb52c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5f390c8-cbd9-47be-81a9-17f0c8f09533 # Italic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b43f0e8-1f5b-43d5-a485-2bb193cdcdce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c4d0d4e-b61f-462b-8bda-32b03f19d292 # Underline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2eeec2c6-9386-4991-bec7-995f13ffb04f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 566a524d-9fa8-4c33-bd5c-fab21ea511ea # Font Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ebe8a7a-04e8-4168-9679-1149867a8dd3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ad17a785-c5da-427c-a726-974392fdbfc3
        userCondition: null
fields:
  6c4d0d4e-b61f-462b-8bda-32b03f19d292: # Underline
    columnSuffix: obyclncu
    contentColumnType: string
    fieldGroup: null
    handle: underline
    instructions: null
    name: Underline
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Underline
            -
              - value
              - underline
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - no-underline
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  566a524d-9fa8-4c33-bd5c-fab21ea511ea: # Font Size
    columnSuffix: xebmntan
    contentColumnType: text
    fieldGroup: null
    handle: fontSize
    instructions: null
    name: 'Font Size'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  907dd3e9-07e3-42f2-8ccb-0a1209635961: # Color
    columnSuffix: vsdhweuh
    contentColumnType: text
    fieldGroup: null
    handle: color
    instructions: null
    name: Color
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  405235d2-95a0-4ef8-a938-989e84dd772d: # Bold
    columnSuffix: xoqaqhxr
    contentColumnType: string
    fieldGroup: null
    handle: bold
    instructions: null
    name: Bold
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Bold
            -
              - value
              - font-bold
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - font-regular
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  a5f390c8-cbd9-47be-81a9-17f0c8f09533: # Italic
    columnSuffix: tkkrqyfz
    contentColumnType: string
    fieldGroup: null
    handle: italic
    instructions: null
    name: Italic
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Italic
            -
              - value
              - italic
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - not-italic
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  f756ef6b-4ea8-4afa-b1e3-e0ce8bb08b3b: # Font Family
    columnSuffix: brccbvri
    contentColumnType: string
    fieldGroup: null
    handle: fontFamily
    instructions: null
    name: 'Font Family'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Figtree
            -
              - value
              - figtree
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Old Standard TT'
            -
              - value
              - oldStandardTt
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Oswald
            -
              - value
              - oswald
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Raleway
            -
              - value
              - raleway
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: templateStyle
name: 'Template Style'
sortOrder: 1
