field: 66ead35a-b47d-4779-9c3d-51d9a704fbf1 # Template H3
fieldLayouts:
  8541ebcf-8bf7-4b7f-b921-2e40c94cb252:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 501a4c3b-59bd-4946-94a7-8e3d95f1d135 # Font Family
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00d6204a-cc3e-416e-b976-4eb963efa872
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bc071cea-0424-402c-af89-51d1626ed94c # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2e70124-bb67-4de6-944a-838771b1d41e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8423fdde-a2a9-4d3e-9a94-5fa750e26021 # Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ebe1d12-1315-4246-a7e1-45ff69f53c9d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b3d94322-f3c2-420d-bce9-611fda671793 # Italic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28ce28a7-8715-4c4b-908d-826035396198
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d1125e42-c305-47a0-98a1-53e8201d4698 # Underline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae5c7ae7-3dc2-4068-a706-bd2104efd4d7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b46b506b-37d8-465f-917e-3307923ddd80 # Font Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 743c4d4e-a3e0-4eca-a3e7-0647753c1ea3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b99a38ac-247b-46f1-b426-9db59b4602cd
        userCondition: null
fields:
  501a4c3b-59bd-4946-94a7-8e3d95f1d135: # Font Family
    columnSuffix: wtlybslx
    contentColumnType: string
    fieldGroup: null
    handle: fontFamily
    instructions: null
    name: 'Font Family'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Figtree
            -
              - value
              - figtree
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Old Standard TT'
            -
              - value
              - oldStandardTt
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Oswald
            -
              - value
              - oswald
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Raleway
            -
              - value
              - raleway
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  8423fdde-a2a9-4d3e-9a94-5fa750e26021: # Bold
    columnSuffix: utzascjr
    contentColumnType: string
    fieldGroup: null
    handle: bold
    instructions: null
    name: Bold
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Bold
            -
              - value
              - font-bold
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - font-regular
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  b3d94322-f3c2-420d-bce9-611fda671793: # Italic
    columnSuffix: abkbwugh
    contentColumnType: string
    fieldGroup: null
    handle: italic
    instructions: null
    name: Italic
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Italic
            -
              - value
              - italic
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - not-italic
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  b46b506b-37d8-465f-917e-3307923ddd80: # Font Size
    columnSuffix: xshopwfv
    contentColumnType: text
    fieldGroup: null
    handle: fontSize
    instructions: null
    name: 'Font Size'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bc071cea-0424-402c-af89-51d1626ed94c: # Color
    columnSuffix: eaieiwqv
    contentColumnType: text
    fieldGroup: null
    handle: color
    instructions: null
    name: Color
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d1125e42-c305-47a0-98a1-53e8201d4698: # Underline
    columnSuffix: pqfarqsp
    contentColumnType: string
    fieldGroup: null
    handle: underline
    instructions: null
    name: Underline
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Underline
            -
              - value
              - underline
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - no-underline
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
handle: templateStyle
name: 'Template Style'
sortOrder: 1
