field: c36661a8-fbe9-4c76-8ade-71d9d7863ed5 # Template H1
fieldLayouts:
  332072a5-74ea-42d2-a8d8-7abbabad071a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d474e292-d759-436a-bedf-609c992f485a # Font Family
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a9c8af9-1dc2-46fa-a47c-181f9ea4f62b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3132ab7-611a-4818-8859-8afa77164586 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39aa620e-3cdb-43c6-81fa-a09b73d2fd1b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 060bfa16-7bd4-4d6b-8a49-da6d4418b154 # Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e86df9c-ac78-482d-903b-fcfc7686397a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d55cee0-10c3-4af9-9f69-0cd60dd6043b # Italic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d6eb88d-20e5-4ba2-9322-643f8375aca3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8b15e4f8-2ce9-4bc6-8a96-0f68325dba65 # Underline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f18c8658-81b5-4d1a-b4a9-c9dc30c8f72d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a3478364-1933-4539-a390-04cc7cd22138 # Font Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16503388-3e2c-412a-b668-d9de55a4bcba
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 58219437-2c60-4e32-81b5-192a94987d80
        userCondition: null
fields:
  8b15e4f8-2ce9-4bc6-8a96-0f68325dba65: # Underline
    columnSuffix: sybxgold
    contentColumnType: string
    fieldGroup: null
    handle: underline
    instructions: null
    name: Underline
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Underline
            -
              - value
              - underline
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - no-underline
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  8d55cee0-10c3-4af9-9f69-0cd60dd6043b: # Italic
    columnSuffix: ykeqtimb
    contentColumnType: string
    fieldGroup: null
    handle: italic
    instructions: null
    name: Italic
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Italic
            -
              - value
              - italic
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - not-italic
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  060bfa16-7bd4-4d6b-8a49-da6d4418b154: # Bold
    columnSuffix: uityqbzs
    contentColumnType: string
    fieldGroup: null
    handle: bold
    instructions: null
    name: Bold
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Bold
            -
              - value
              - font-bold
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - font-regular
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  a3478364-1933-4539-a390-04cc7cd22138: # Font Size
    columnSuffix: lztevqrh
    contentColumnType: text
    fieldGroup: null
    handle: fontSize
    instructions: null
    name: 'Font Size'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c3132ab7-611a-4818-8859-8afa77164586: # Color
    columnSuffix: kwvwrjrd
    contentColumnType: text
    fieldGroup: null
    handle: color
    instructions: null
    name: Color
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d474e292-d759-436a-bedf-609c992f485a: # Font Family
    columnSuffix: sgxpshpl
    contentColumnType: string
    fieldGroup: null
    handle: fontFamily
    instructions: null
    name: 'Font Family'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Figtree
            -
              - value
              - figtree
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Old Standard TT'
            -
              - value
              - oldStandardTT
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Oswald
            -
              - value
              - oswald
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Raleway
            -
              - value
              - raleway
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: templateStyle
name: 'Template Style'
sortOrder: 1
