fieldLayouts:
  6693253b-dfed-4d9c-b3ba-4d9490fea497:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 43a026fa-370e-4558-8812-b2bdf2329e46
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 981031c7-feb9-4f10-853f-b9c28a743f8a # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a91d6d0b-1b58-41f6-8a10-17f5d27c4ad9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f4404f7-5361-47e6-b2bc-cf21110f756d
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 825f5194-2354-488a-b7fe-80751d17308f # Theologisch thema
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
