fieldLayouts:
  a25be9cc-164f-4171-8472-bcedd76d02f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d09063c0-f000-4b7c-bf38-822f9f6302e8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2edfb3a3-a0e7-4841-9f21-c344783209eb
        userCondition: null
handle: projects
hasTitleField: false
name: 'Mijn projecten'
section: 6e514aec-1ff4-46e2-9df3-77342b85dafa # Mijn projecten
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
