tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        fieldUid: 0a7e9283-91f3-47b3-b233-afac5a1e069f # User Role
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: df2cdac0-5197-4f3b-87ab-fed570e17756
        userCondition: null
        warning: null
        width: 100
    name: User
    uid: 59dcc8df-fe05-4f71-b476-60bb6482ea51
    userCondition: null
