fieldLayouts:
  1a0d2b91-6c03-4ed8-9515-0803e29c8388:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3622a70a-13d9-4a8a-bd33-ac92262b97c1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9758ecba-55f7-4b1c-bd00-65bc5f35dca2
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
