columnSuffix: null
contentColumnType: string
fieldGroup: 2d120b16-ef61-4e55-902e-535a963add67 # Project
handle: theme
instructions: null
name: Thema
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: 1
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:d37fca0b-7d62-4434-ba98-ff04fd4953fb' # Thema
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
