defaultPlacement: end
enableVersioning: true
handle: project
name: Project
propagationMethod: all
siteSettings:
  793e9deb-b429-4d9b-b78a-54f610e0bb24: # cms-eindwerk
    enabledByDefault: true
    hasUrls: true
    template: _pages\projectDetail
    uriFormat: 'projecten/{slug}'
type: channel
