defaultPlacement: end
enableVersioning: true
handle: projects
name: 'Mijn projecten'
propagationMethod: all
siteSettings:
  793e9deb-b429-4d9b-b78a-54f610e0bb24: # cms-eindwerk
    enabledByDefault: true
    hasUrls: true
    template: _pages\projects.twig
    uriFormat: projecten
type: single
