defaultPlacement: end
enableVersioning: true
handle: theologicalTheme
name: 'Theologisch thema'
propagationMethod: all
siteSettings:
  793e9deb-b429-4d9b-b78a-54f610e0bb24: # cms-eindwerk
    enabledByDefault: true
    hasUrls: true
    template: _pages\themeDetail
    uriFormat: 'theologisch/{slug}'
type: channel
