defaultPlacement: end
enableVersioning: true
handle: theologicalThemes
name: 'Theologische thema''s'
propagationMethod: all
siteSettings:
  793e9deb-b429-4d9b-b78a-54f610e0bb24: # cms-eindwerk
    enabledByDefault: true
    hasUrls: true
    template: _pages/themes
    uriFormat: theologisch
type: single
